version: "3.1"
services:
  zookeeper:
    image: "zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: "yes"

  zoonavigator:
    image: elkozmon/zoonavigator
    environment:
      CONNECTION_MYZK_CONN: "zookeeper:2181"
      AUTO_CONNECT_CONNECTION_ID: "MYZK"
    depends_on:
      - zookeeper
    ports:
      - 9000:9000
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: always

  store:
    image: docker.io/andrew-delph/store:store_image
    depends_on:
      - zookeeper
      - nginx
    restart: always
