version: "3.1"
services:
  # zookeeper:
  #   image: "zookeeper:latest"
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ZOO_MY_ID: 1
  #     ZOO_PORT: 2181
  #     ALLOW_ANONYMOUS_LOGIN: "yes"
  #   restart: always

  # zoonavigator:
  #   image: elkozmon/zoonavigator
  #   environment:
  #     CONNECTION_MYZK_CONN: "zookeeper:2181"
  #     AUTO_CONNECT_CONNECTION_ID: "MYZK"
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - 9000:9000
  #   restart: always

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: always

  store:
    image: docker.io/andrew-delph/store:store_image
    scale: 10
    depends_on:
      # - zookeeper
      - nginx
    # restart: always
    volumes:
      - /tmp/store_data:/store
