manager:
  replica_count: 3
  read_quorum: 2
  write_quorum: 2
  default_timeout: 10
  req_channel_size: 20
  workers_count: 100
  partition_count: 100
  partition_concurrency: 5
  partition_buckets: 1000
  partition_replicas: 2
  data_path: "/data/storage"
  load: 1.25
  ring_debounce: 7.5
consensus:
  epoch_time: 500
  data_path: "/data/raft"
  enable_logs: false
  auto_bootstrap: true
  bootstrap_timeout: 10
gossip:
  enable_logs: false
  init_members:
    - "store:8081"
    - "store-0:8081"
    - "store-0.store.default:8081"
storage:
  data_path: "/data/storage"
rpc:
  port: 7070
  default_timeout: 7
http:
  default_timeout: 20
