manager:
  replica_count: 5
  read_quorum: 2
  write_quorum: 3
  default_timeout: 5
  req_channel_size: 1000
  workers_count: 100
  partition_concurrency: 1
  partition_count: 100
  partition_buckets: 1000
  partition_replicas: 2
  data_path: "/data/storage"
  load: 2.1
  ring_debounce: 7.5
consensus:
  epoch_time: 100000000
  data_path: "/data/raft"
  enable_logs: false
  auto_bootstrap: true
  bootstrap_timeout: 100000000
gossip:
  enable_logs: false
  init_members:
    - "store:8081"
    - "store-0:8081"
storage:
  data_path: "/data/storage"
rpc:
  port: 7070
http:
  default_timeout: 10
