manager:
  replica_count: 4
  read_quorum: 3
  write_quorum: 2
  default_timeout: 2
  workers_count: 20
  req_channel_size: 1000
  partition_count: 100
  partition_buckets: 500
  data_path: "/store/data"
consensus:
  epoch_time: 30
  data_path: "/store/raft"
  enable_logs: false
  auto_bootstrap: true
  bootstrap_timeout: 1
gossip:
  init_members:
    - "store:8081"
storage:
  data_path: "/store/data"
rpc:
  port: 7070
http:
  default_timeout: 1
