manager:
  replica_count: 3
  read_quorum: 2
  write_quorum: 2
  partition_count: 100
  partition_buckets: 500
  data_path: "/store/data"
consensus:
  epoch_time: 5
  data_path: "/store/raft"
  enable_logs: false
  auto_bootstrap: true
  bootstrap_timeout: 1
gossip:
  init_members:
    - "store:8081"
storage:
  data_path: "/store/data"
