manager:
  replica_count: 9
  write_quorum: 99
  read_quorum: 999
  partition_count: 9999
  partition_buckets: 99999
  partition_concurrency: 991
  data_path: "/tmp/store/data"
  thread_requests: true
consensus:
  epoch_time: 9
  data_path: "/tmp/store/raft"
  enable_logs: true
  auto_bootstrap: false
  bootstrap_timeout: 1
gossip:
  init_members:
    - "test:1"
    - "test:2"
storage:
  data_path: "/tmp/store/data"
http:
  default_timeout: 33
